// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYypjIf509bH4XJdqqSm8pE4M1yn1wbu0',
    appId: '1:642905262049:web:17daa2c9ca0f4048a934a0',
    messagingSenderId: '642905262049',
    projectId: 'maribel-wellness',
    authDomain: 'maribel-wellness.firebaseapp.com',
    storageBucket: 'maribel-wellness.firebasestorage.app',
    measurementId: 'G-HWED4FXMYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl0zTqLDBhrejCg4bNQDQF18DfhRUXISc',
    appId: '1:642905262049:android:c8a27342e5e0c17aa934a0',
    messagingSenderId: '642905262049',
    projectId: 'maribel-wellness',
    storageBucket: 'maribel-wellness.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCz9pgHoskzMAP39EuX2gNvCkgD5PjPfI',
    appId: '1:642905262049:ios:7aa91447f7601b4da934a0',
    messagingSenderId: '642905262049',
    projectId: 'maribel-wellness',
    storageBucket: 'maribel-wellness.firebasestorage.app',
    iosBundleId: 'com.example.maribelWellnessCentreApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCz9pgHoskzMAP39EuX2gNvCkgD5PjPfI',
    appId: '1:642905262049:ios:7aa91447f7601b4da934a0',
    messagingSenderId: '642905262049',
    projectId: 'maribel-wellness',
    storageBucket: 'maribel-wellness.firebasestorage.app',
    iosBundleId: 'com.example.maribelWellnessCentreApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYypjIf509bH4XJdqqSm8pE4M1yn1wbu0',
    appId: '1:642905262049:web:f5391c7f69779e9ba934a0',
    messagingSenderId: '642905262049',
    projectId: 'maribel-wellness',
    authDomain: 'maribel-wellness.firebaseapp.com',
    storageBucket: 'maribel-wellness.firebasestorage.app',
    measurementId: 'G-538E42WT0K',
  );
}
